services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: nyt_app
    volumes:
      - ./app:/var/www
    env_file:
      - .env
    networks:
      - nyt-app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nyt_nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./app:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nyt-app-network

  redis:
    image: redis:alpine
    container_name: nyt_redis
    ports:
      - "16379:6379"
    networks:
      - nyt-app-network

networks:
  nyt-app-network:
    driver: bridge