openapi: 3.0.0
info:
  title: 'My NYT Bestsellers API'
  version: 1.0.0
servers:
  -
    url: 'http://localhost/api'
    description: 'Local API server'
paths:
  /api/nyt/bestsellers:
    get:
      summary: 'get bestsellers from NYT'
      operationId: 219f96b9982cf7142c3ca2f30aa58b2e
      parameters:
        -
          name: author
          in: query
          description: 'Filter by Author'
          required: false
          schema:
            type: string
        -
          name: title
          in: query
          description: 'Filter by Title'
          required: false
          schema:
            type: string
        -
          name: isbn
          in: query
          description: 'Filter by ISBN'
          required: false
          schema:
            type: string
        -
          name: offset
          in: query
          description: 'Page offset'
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data: { type: array, items: { type: object } }
                type: object
        '403':
          description: 'Unauthorized access'
